name: 'comment-notes'
description: 'Save PR comments as git-notes in merged PRs'
inputs:
  github-token:
    description: Automatically injected token used to update commit.
    required: true
  comment-template:
    description: 'Template used for each comment.'
    default: |
      ----------------------------
      $comment.user.login:

      $comment.body

    required: true
  ignore-authors:
    description: A comma-separated string of authors NOT to include.
    default: ''
    required: false
  ref:
    description: The namespace used to store the notes.
    default: ''
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
