on:
  pull_request:
    types: [closed]

jobs:
  comment-notes:
    runs-on: ubuntu-latest
    name: 'comment-notes'
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: read
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: Commit notes
        id: commit-notes
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'pr_comments'
